spring:
  data:
    mongodb:
      uri: mongodb://ecaldas-git:96xFyjQI79Mu237Y@cluster0-shard-00-00-jlss8.mongodb.net:27017,cluster0-shard-00-01-jlss8.mongodb.net:27017,cluster0-shard-00-02-jlss8.mongodb.net:27017/mutant-dna?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true